# Generated by Django 3.0.10 on 2020-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=40)),
                ('size', models.IntegerField()),
                ('image', models.FilePathField(path='/static/')),
            ],
        ),
    ]
