# Generated by Django 3.0.10 on 2020-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='size',
        ),
        migrations.AddField(
            model_name='link',
            name='dest',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='alt',
            field=models.CharField(max_length=100),
        ),
    ]
