# Generated by Django 3.0.10 on 2020-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20201008_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.FilePathField(path='static/misc/link_in_bio/img/'),
        ),
    ]
