# Generated by Django 3.0.10 on 2020-10-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_auto_20201008_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('title',)},
        ),
    ]
